-- User Subsystem
DROP TABLE IF EXISTS parking_records;
DROP TABLE IF EXISTS parking_spots;
DROP TABLE IF EXISTS pricing_rules;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS managers;
DROP TABLE IF EXISTS parking_lots;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS system_admins;
DROP TABLE IF EXISTS wallet_log;
DROP TABLE IF EXISTS user_wallet;
DROP TABLE IF EXISTS fee_rule;
DROP TABLE IF EXISTS parking_order;
DROP TABLE IF EXISTS parking_space;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS audit_log;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash CHAR(64) NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100),
    nickname VARCHAR(50),
    avatar_url VARCHAR(255),
    balance DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TINYINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    sender_role VARCHAR(20),
    receiver_id BIGINT NOT NULL,
    receiver_role VARCHAR(20),
    content VARCHAR(1000),
    type VARCHAR(20),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20),
    old_value VARCHAR(100),
    new_value VARCHAR(100),
    status TINYINT DEFAULT 0,
    reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    handled_at TIMESTAMP,
    handler_id BIGINT
);

CREATE TABLE IF NOT EXISTS wallet_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    type TINYINT,
    balance_after DECIMAL(10,2),
    order_id BIGINT,
    remark VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicles (
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plate_number VARCHAR(20) UNIQUE NOT NULL,
    brand VARCHAR(50),
    model VARCHAR(50),
    color VARCHAR(20),
    vehicle_type TINYINT,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_wallet (
    wallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    balance DECIMAL(10,2) DEFAULT 0.00,
    version INT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    type TINYINT,
    remark VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    title VARCHAR(100),
    tax_no VARCHAR(50),
    status TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monthly_cards (
    card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    plate_number VARCHAR(20),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System Admin Subsystem
CREATE TABLE IF NOT EXISTS system_admins (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash CHAR(64) NOT NULL,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    role VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

CREATE TABLE IF NOT EXISTS managers (
    manager_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash CHAR(64) NOT NULL,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Parking Lot Subsystem
CREATE TABLE IF NOT EXISTS parking_lots (
    lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    total_spots INT DEFAULT 0,
    available_spots INT DEFAULT 0,
    manager_id BIGINT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parking_spots (
    spot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL,
    spot_number VARCHAR(20) NOT NULL,
    spot_type TINYINT DEFAULT 1,
    is_occupied BOOLEAN DEFAULT FALSE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pricing_rules (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL,
    vehicle_type TINYINT,
    base_duration INT DEFAULT 0,
    base_price DECIMAL(6,2) DEFAULT 0.00,
    extra_price_per_hour DECIMAL(6,2) DEFAULT 0.00,
    daily_cap DECIMAL(6,2),
    effective_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS parking_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    spot_id BIGINT NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP,
    duration_minutes INT,
    amount DECIMAL(8,2) DEFAULT 0.00,
    paid_amount DECIMAL(8,2) DEFAULT 0.00,
    payment_status TINYINT DEFAULT 0,
    payment_method VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_records_lot_entry ON parking_records(lot_id, entry_time);
CREATE INDEX IF NOT EXISTS idx_spots_lot_number ON parking_spots(lot_id, spot_number);

-- Initial Data
MERGE INTO system_admins (username, password_hash, role) 
KEY(username) 
VALUES ('admin', '$2a$10$EblZqNptyYpXnRenCdTA7.Wc4M9.A3M/6y6kG1gE6.7J6.7J6.7J6', 'super');

MERGE INTO parking_lots (name, longitude, latitude, total_spots, available_spots, status)
KEY(name)
VALUES ('我的停车场', 127.2128487, 45.7478858, 100, 50, 1);
